# The Name of our automated assembly line
name: Corporate CI-CD Assembly Line

# TRIGGER: Wake up the automation every time a developer merges code to main
on:
  push:
    branches:
      - main

# THE TASKS (The Automated Conveyor Belt)
jobs:
  continuous-integration:
    name: 🧪 Run CI Security & Quality Gates
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Simulating Code Quality Scan
        run: |
          echo "Scanning backend Python files..."
          echo "Checking syntax compliance... SUCCESS!"

  continuous-deployment:
    name: 📦 Run CD Container Orchestration
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Executing Remote SSH Commands to Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/docker-best-practices
            git pull origin main
            docker compose up -d --build
